In [30]:
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
df = pd.read_csv('yelp_reviews.csv')

In [32]:
X_train, X_test, y_train, y_test = train_test_split(df['text'].values, df['pos_neg'].values, test_size=0.2)




In [33]:
vectorizer = CountVectorizer(lowercase=True)

In [34]:
X_train_matrix = vectorizer.fit_transform(X_train)
X_test_matrix = vectorizer.transform(X_test)

In [35]:
X_train_tensor = torch.tensor(X_train_matrix.toarray(), dtype=torch.float)
X_test_tensor = torch.tensor(X_test_matrix.toarray(), dtype=torch.float)

In [36]:
w = torch.randn(X_train_tensor.shape[1], dtype=torch.float, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
w

tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)

In [37]:
y_train_tensor = torch.tensor(y_train, dtype=torch.float)
y_test_tensor = torch.tensor(y_test, dtype=torch.float)
w

tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)

In [38]:
learning_rate = 0.001

In [ ]:
for epoch in range(10):  # consider each data point once in each epoch
    for i in range(len(X_train_tensor)):  # iterate over all data points
        prediction = w @ X_train_tensor[i] + b
        actual = y_train_tensor[i]
        loss = torch.log(1 + torch.exp(- actual * prediction))
        loss.backward()

        with torch.no_grad():
            w -= learning_rate * w.grad
            b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()
        print(w)
        

tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1714,  1.6622, -1.0917,  ...,

tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1754,  1.6612, -1.0917,  ...,

tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1784,  1.6612, -1.0917,  ...,

tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1815,  1.6602, -1.0917,  ...,

tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1803,  1.6602, -1.0917,  ...,

tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6602, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6582, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6582, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6582, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1823,  1.6582, -1.0917,  ...,

tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1833,  1.6571, -1.0917,  ...,

tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ..., -0.8650,  0.1228, -0.7100],
       requires_grad=True)
tensor([-0.1843,  1.6571, -1.0917,  ...,

In [25]:
w

tensor([nan, nan, nan,  ..., nan, nan, nan], requires_grad=True)

In [23]:
correct = 0

for i in range(len(X_test_tensor)):
    prediction = w @ X_test_tensor[i] + b
    actual = y_test_tensor[i]
    if (prediction > 0 and actual == 1) or (prediction < 0 and actual == -1):
        correct += 1

In [24]:
correct

0