In [20]:
import pandas as pd
import re
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer


In [2]:
df = pd.read_csv('reviews.csv')


In [3]:
df.drop('Unnamed: 0', axis=1)


review_id                 user_id             business_id  \
0      x7mDIiDB3jEiPGPHOmDzyw  msQe1u7Z_XuqjGoqhB0J5g  iCQpiavjjPzJ5_3gPD5Ebg   
1      dDl8zu1vWPdKGihJrwQbpw  msQe1u7Z_XuqjGoqhB0J5g  pomGBqfbxcqPv14c3XH-ZQ   
2      LZp4UX5zK3e-c5ZGSeo3kA  msQe1u7Z_XuqjGoqhB0J5g  jtQARsP6P-LbkyjbO1qNGg   
3      Er4NBWCmCD4nM8_p1GRdow  msQe1u7Z_XuqjGoqhB0J5g  elqbBhBfElMNSrjFqW3now   
4      jsDu6QEJHbwP2Blom1PLCA  msQe1u7Z_XuqjGoqhB0J5g  Ums3gaP2qM3W1XcA5r6SsQ   
...                       ...                     ...                     ...   
99995  2df29zvymwCxWJOmG0f_Gg  7RgoC1RzgpL5ZztwOO-VZQ  22LyWivLY_y_b3ohASfP2Q   
99996  yXsK_sORFdZS57erFFJ-FQ  7RgoC1RzgpL5ZztwOO-VZQ  K6u-k0Z4OmQhHNPSxk3vvA   
99997  L6ANzSBuP_Ow63bFlMcqRA  7RgoC1RzgpL5ZztwOO-VZQ  WgpxfYBGWolWEK8IQmXFJQ   
99998  8YmVjEobyzJ1hzS33np58A  7RgoC1RzgpL5ZztwOO-VZQ  _ax_jfISiBZ4JSTHrI4xJA   
99999  DaMywzhTmlepBWCCOadS-w  7RgoC1RzgpL5ZztwOO-VZQ  -wpNQQYtqlmQ9Rcwhgm9iw   

       stars        date                                               text  \
0          2  2011-02-25  The pizza was okay. Not the best I've had. I p...   
1          5  2012-11-13  I love this place! My fiance And I go here atl...   
2          1  2014-10-23  Terrible. Dry corn bread. Rib tips were all fa...   
3          2  2011-02-25  Back in 2005-2007 this place was my FAVORITE t...   
4          5  2014-09-05  Delicious healthy food. The steak is amazing. ...   
...      ...         ...                                                ...   
99995      3  2012-11-10  We ate there for the first time last week on t...   
99996      5  2012-10-12  Touch of Tranquility Massage is amazing. I cou...   
99997      5  2014-03-21  I had the quiche today (broccoli) and it was e...   
99998      3  2015-04-25  This place is on my way home and has mixed rev...   
99999      5  2016-11-11  Great service, knowledgeable people, and very ...   

       useful  funny  cool  
0           0      0     0  
1           0      0     0  
2           3      1     1  
3           2      0     0  
4           0      0     0  
...       ...    ...   ...  
99995       1      0     0  
99996       0      0     0  
99997       0      0     0  
99998       1      0     0  
99999      13      1    13  

[100000 rows x 9 columns]

In [4]:
df = df.sample(frac=0.1)

In [8]:
def decide_pos_neg(stars):
    if stars < 3:
        return 1
    elif stars == 3:
        return -1
    else:
        return 0

In [10]:
df['pos_neg'] = df['stars'].apply(decide_pos_neg)

In [12]:
df = df[df['pos_neg'] != -1]

In [16]:
df.to_json('yelp_reviews.json')

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df['text'].values, df['pos_neg'].values, test_size=0.2)

In [18]:
# converts a collection of text documents to a matrix of token counts
vectorizer = CountVectorizer(lowercase=True)

In [19]:
# Learn a vocabulary dictionary of all tokens in X_train (list of reviews)
vectorizer.fit_transform(X_train)

<7320x22731 sparse matrix of type '<class 'numpy.int64'>'
	with 474156 stored elements in Compressed Sparse Row format>

In [22]:
classifier = LogisticRegression()

In [23]:
# vectorizer.transform transforms X_train into a document term matrix
# this fits the linear regression model using least squares regression
classifier.fit(vectorizer.transform(X_train), y_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [24]:
print("Score:", classifier.score(vectorizer.transform(X_test), y_test))

Score: 0.9360655737704918


In [25]:
classifier.predict(vectorizer.transform(["Terrible food, terrible service. Would never reccomend to a friend"]))


array([1])

In [26]:
classifier.predict(vectorizer.transform(X_test))

array([1, 1, 0, ..., 1, 0, 0])

In [27]:
y_test

array([1, 1, 0, ..., 0, 0, 0])